{pkgs, vars, ...}:{
  home.packages = with pkgs; [
    blender-hip
    brightnessctl
    cinny-desktop
    comma
    wlx-overlay-s
    emacs
    firefox
    fzf
    gamescope
    gimp
    grim
    gtklock
    gzdoom
    hyfetch
    inkscape
    kanshi
    kdePackages.ark
    libgpod
    libimobiledevice
    libreoffice
    mpc
    nemo
    nextcloud-client
    openrct2
    openscad
    openutau
    pamixer
    pavucontrol
    playerctl
    prismlauncher
    prusa-slicer
    slurp
    swaybg
    swaynotificationcenter
    udiskie
    v4l-utils
    vesktop
    vlc
    wl-clipboard
    wlr-randr
    xfce.ristretto
    xfce.tumbler
  ]; #++ (if !vars.isNixOS then [nixgl.nixGLIntel] else []);
}
