# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  hardware.bluetooth = {
    enable = true;
    powerOnBoot = true;
    settings = {
      General.Experimental = true;
    };
    input = { 
      General.ClassicBondedOnly = false;
      General.UserspaceHID = true;
    };
  };
  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ "vfio_pci" "vfio" "vfio_iommu_type1" "vendor-reset" ];
  boot.kernelModules = [ "kvm-intel" "vfio_virqfd" "vhost-net" "v4l2loopback" "12c-dev" ];
  boot.extraModulePackages = with config.boot.kernelPackages; [ v4l2loopback vendor-reset];
  boot.extraModprobeConfig = ''
    options vfio-pci ids=1002:6fdf,1002:aaf0,1b21:1242
    options v4l2loopback devices=2 video_nr=1,2 card_label="OBS Cam, Virt Cam" exclusive_caps=1
  '';
  boot.blacklistedKernelModules = ["nouveau"];
  boot.kernelParams = [ "amdgpu.ppfeaturemask=0xffffffff" "intel_iommu=on" "iommu=pt" "pcie_acs_override=downstream,multifunction" "preempt=voluntary" "module_blacklist=nouveau" ];


  fileSystems."/" =
    { device = "/dev/disk/by-uuid/3367079b-0477-4088-b57d-90a8098bdef7";
      fsType = "xfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8DE9-D26C";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };
  fileSystems."/mnt/vms" = 
    { device = "/dev/disk/by-uuid/9443885e-d2b3-44a1-aec2-540de7f5c832";
      fsType = "xfs";
      options = [ "x-gvfs-show" ];
    };
  fileSystems."/mnt/data" = 
    { device = "/dev/disk/by-uuid/a4a08196-cedc-4be2-988d-d28eb41492c0";
      fsType = "xfs";
      options = [ "x-gvfs-show" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/f7e4a77c-0936-445c-8ce9-0386e9e81656"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp7s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
